### ISSUE TITLE
form posting with use:enhance

### ISSUE THREAD

**Issue by bamthomas** [davipon/svelte-component-test-recipes#30]
First of all thank you for all the recipes it helped me a lot to test my app.
I'm trying to make unit tests on form posting with `use:enhance`. I'm having a 

```
Error: Cannot call applyAction(...) on the server
    at file:///home/dev/src/iroco-app-client/node_modules/@sveltejs/kit/src/runtime/app/forms.js:11:9
    at fallback_callback (file:///home/dev/src/iroco-app-client/node_modules/@sveltejs/kit/src/runtime/app/forms.js:56:4)
    at HTMLFormElement.handle_submit (file:///home/dev/src/iroco-app-client/node_modules/@sveltejs/kit/src/runtime/app/forms.js:116:3)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
```

I haven't found tests on this on the sveltekit repo other than the e2e tests, neither in this repository.

Do you have examples or insights to make it work?

**Comment by davipon** [comment]
I have limited knowledge about testing forms with `use:enhance` since we're not using SSR in my work project.
Maybe e2e testing is a better approach.

Do you have a repro or sandbox link?
